In [9]:
#IT20188054
#Benthota Arachchi B.A.T.P

In [10]:
from bs4 import BeautifulSoup 
import pandas as pd
from urllib.request import Request, urlopen

In [11]:
req = Request(
    url = 'https://www.guess.com/us/en/women/apparel/sale/denim', 
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/192.168.56.1 Safari/537.36 QIHU 360SE'}
)
webpage = urlopen(req).read()

In [12]:
doc = BeautifulSoup(webpage, 'html.parser')

In [13]:
products = products = doc.find_all('div', {'class': 'product-grid__column'})
#products[]

In [14]:
df = pd.DataFrame(columns=['Product No', 'Product Name', 'Old Price', 'New Price', 'Discount'])
i = 0

#Create dataframe to scrape data
for prod in products:
  i=i+1
  #prodname
  prodname = prod.find('a', {'class': 'link product-tile__link'}).text.strip()

  #old price
  oldprice = prod.find('span', {'class': 'price__strike-through'}).text.strip()

  #new price
  newprice = prod.find('span', {'class': 'price__red-color text-nowrap'}).text.strip().split('\n')[1]

  #discount
  discount = prod.find('span', {'class': 'price__red-color d-inline-block text-nowrap'}).text.strip().split(' ')[0].split('(')[1]

  row = pd.DataFrame([[i,prodname,oldprice,newprice, discount]], columns=['Product No', 'Product Name', 'Old Price', 'New Price', 'Discount'])
  df = pd.concat([df,row], ignore_index=True)

In [15]:
df

,Product No,Product Name,Old Price,New Price,Discount
0,1,Eco Pop '70s Split Hem Jeans,$148.00,$88.80,40%
1,2,Eco Super High-Rise Wide Leg Jeans,$148.00,$74.00,50%
2,3,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
3,4,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
4,5,Emerson Denim Skirt,$128.00,$76.80,40%
5,6,Jossy High-Rise Flare Jeans,$158.00,$79.00,50%
6,7,1981 Pinstripe Skinny Jeans,$108.00,$64.80,40%
7,8,Emerson Denim Skirt,$128.00,$76.80,40%
8,9,Claudia Eyelet Shorts,$98.00,$49.00,50%
9,10,1981 Pinstripe Skinny Jeans,$108.00,$64.80,40%
10,11,Lace Exposed Button Mom Jeans,$128.00,$64.00,50%
11,12,Stiletto No. 97 Jean,$150.00,$119.99,20%
12,13,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
13,14,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
14,15,Claudia Eyelet Shorts,$98.00,$49.00,50%
15,16,Lace Exposed Button Mom Jeans,$128.00,$64.00,50%
16,17,Lace Denim Mini Skirt,$98.00,$58.80,40%
17,18,1981 Lace Skinny Jeans,$138.00,$82.80,40%
18,19,Lace Denim Mini Skirt,$98.00,$58.80,40%
19,20,Neva Jumpsuit,$148.00,$88.80,40%
20,21,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
21,22,Claudia Eyelet Shorts,$98.00,$49.00,50%
22,23,Manila Shorts,$89.00,$44.50,50%
23,24,Eco Neva Jumpsuit,$148.00,$88.80,40%
24,25,Manila Shorts,$89.00,$44.50,50%
25,26,1981 Pinstripe Skinny Jeans,$108.00,$64.80,40%
26,27,1981 Lace Skinny Jeans,$138.00,$69.00,50%
27,28,1981 Metallic Floral Skinny Jeans,$148.00,$74.00,50%
28,29,Printed Sexy Bootcut Jeans,$168.00,$84.00,50%
29,30,1981 Destroyed High-Rise Skinny Jeans,$108.00,$64.80,40%
30,31,Ultimate Shimmer Skinny Jeans,$128.00,$64.00,50%
31,32,1981 Destroyed High-Rise Skinny Jeans,$108.00,$81.00,25%
32,33,1981 Faux-Leather Waist Straight Jeans,$128.00,$64.00,50%
33,34,1981 Coated Skinny Jeans,$128.00,$64.00,50%
34,35,Hollywood Straight Jeans,$98.00,$58.80,40%
35,36,1981 Coated Skinny Jeans,$128.00,$64.00,50%

In [16]:
df.to_excel('IT20188054.xlsx', index=False)

In [18]:
pd.read_excel('IT20188054.xlsx')

,Product No,Product Name,Old Price,New Price,Discount
0,1,Eco Pop '70s Split Hem Jeans,$148.00,$88.80,40%
1,2,Eco Super High-Rise Wide Leg Jeans,$148.00,$74.00,50%
2,3,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
3,4,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
4,5,Emerson Denim Skirt,$128.00,$76.80,40%
5,6,Jossy High-Rise Flare Jeans,$158.00,$79.00,50%
6,7,1981 Pinstripe Skinny Jeans,$108.00,$64.80,40%
7,8,Emerson Denim Skirt,$128.00,$76.80,40%
8,9,Claudia Eyelet Shorts,$98.00,$49.00,50%
9,10,1981 Pinstripe Skinny Jeans,$108.00,$64.80,40%
10,11,Lace Exposed Button Mom Jeans,$128.00,$64.00,50%
11,12,Stiletto No. 97 Jean,$150.00,$119.99,20%
12,13,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
13,14,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
14,15,Claudia Eyelet Shorts,$98.00,$49.00,50%
15,16,Lace Exposed Button Mom Jeans,$128.00,$64.00,50%
16,17,Lace Denim Mini Skirt,$98.00,$58.80,40%
17,18,1981 Lace Skinny Jeans,$138.00,$82.80,40%
18,19,Lace Denim Mini Skirt,$98.00,$58.80,40%
19,20,Neva Jumpsuit,$148.00,$88.80,40%
20,21,1981 Eyelet Straight Jeans,$138.00,$82.80,40%
21,22,Claudia Eyelet Shorts,$98.00,$49.00,50%
22,23,Manila Shorts,$89.00,$44.50,50%
23,24,Eco Neva Jumpsuit,$148.00,$88.80,40%
24,25,Manila Shorts,$89.00,$44.50,50%
25,26,1981 Pinstripe Skinny Jeans,$108.00,$64.80,40%
26,27,1981 Lace Skinny Jeans,$138.00,$69.00,50%
27,28,1981 Metallic Floral Skinny Jeans,$148.00,$74.00,50%
28,29,Printed Sexy Bootcut Jeans,$168.00,$84.00,50%
29,30,1981 Destroyed High-Rise Skinny Jeans,$108.00,$64.80,40%
30,31,Ultimate Shimmer Skinny Jeans,$128.00,$64.00,50%
31,32,1981 Destroyed High-Rise Skinny Jeans,$108.00,$81.00,25%
32,33,1981 Faux-Leather Waist Straight Jeans,$128.00,$64.00,50%
33,34,1981 Coated Skinny Jeans,$128.00,$64.00,50%
34,35,Hollywood Straight Jeans,$98.00,$58.80,40%
35,36,1981 Coated Skinny Jeans,$128.00,$64.00,50%